### ISSUE TITLE
JetPack-4.6 branch no laser scan topic

### ISSUE THREAD

**Issue by prat1kbhujbal** [DreamVu/PAL-USB#11]
Hi,
I tried the jetpack version on jetson Xavier but didn't get the scan topic for laser scan. So do I need to download any other package like the one mentioned in the main branch that has mentioned downloading the pal-navigation package?

**Comment by rajat974** [comment]
Yes, you should use the main branch. The main branch contains the laser scan topic. The main branch also works on Jetpack 4.6On Oct 5, 2022, at 9:36 PM, Pratik Bhujbal ***@***.***> wrote:﻿
Hi,
I tried the jetpack version on jetson Xavier but didn't get the scan topic for laser scan. So do I need to download any other package like the one mentioned in the main branch that has mentioned to download package pal-navigation?

**Comment by prat1kbhujbal** [comment]
HI I tried building it but gives this warning 
`warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.4`
