### ISSUE TITLE
Error while building ros repository

### ISSUE THREAD

**Issue by prat1kbhujbal** [DreamVu/PAL-USB#12]
Hi,
I tried building your navigation and camera repository as instructed in documentation but gives this error
System specs: Jetson Xavier and ROS Melodic
`make[2]: *** No rule to make target '/home/myusername/dreanvu/PAL/installations/../lib/libPAL_Track.so', needed by '/home/myusername/catkin_ws/devel/lib/dreamvu_pal_camera/detectall'. Stop. CMakeFiles/Makefile2:1701: recipe for target 'dreamvu_pal_camera/CMakeFiles/detectall.dir/all' failed`

**Comment by kishk31** [comment]
Dear Pratik Bhujbal,

Thanks for the patience.
We have updated the PAL-USB repo with the latest release.
So please try using the below command for updating with SDK with the latest changes.

sudo apt update
sudo dpkg --remove --force-all pal && sudo apt autoremove
sudo apt install pal

**Comment by prat1kbhujbal** [comment]
Thank you will try and let you know.

**Comment by DreamVu-Support** [comment]
Welcome DreamVu/PAL-USB!
 

 You are invited to access DreamVu Customer Support&#39;s Customer Self Service Portal
 

 

 

 

 By accessing this portal, you can track your requests online,
 access knowledge base and join the community forums.
 ACCEPT THE INVITATION


 

 

 

 Your user name is ***@***.*** | You can also click here to accept the invitation 
 

 

 

 

 

 Thank you, DreamVu Customer Support Administrator
 

 

 



This email has been sent to you&#x28;reply&#x2b;a354cbnpfgvnesflo457kqwbogb2vevbnhhfhmfdfu&#x40;reply.github.com&#x29; by rajat&#x40;dreamvu.com from DreamVu Customer Support. Please contact the sender&#x28;rajat&#x40;dreamvu.com&#x29; for any clarifications.

**Comment by prat1kbhujbal** [comment]
Hi, it didn't resolve the issue still have the same error while building. Also, there was no dreamvu_pal_navigation package inside SDK.

**Comment by DreamVu-Support** [comment]
Welcome DreamVu/PAL-USB!
 

 You are invited to access DreamVu Customer Support&#39;s Customer Self Service Portal
 

 

 

 

 By accessing this portal, you can track your requests online,
 access knowledge base and join the community forums.
 ACCEPT THE INVITATION


 

 

 

 Your user name is ***@***.*** | You can also click here to accept the invitation 
 

 

 

 

 

 Thank you, DreamVu Customer Support Administrator
 

 

 



This email has been sent to you&#x28;reply&#x2b;a354cbohr373iomnttx5adwbogce7evbnhhfhmfdfu&#x40;reply.github.com&#x29; by rajat&#x40;dreamvu.com from DreamVu Customer Support. Please contact the sender&#x28;rajat&#x40;dreamvu.com&#x29; for any clarifications.

**Comment by kishk31** [comment]
Dear Pratik Bhujbal,

Thanks for the patience.
We need to have a remote debugging session to resolve the issue.
Please mail few convenient time slots to support@dreamvu.com.

**Comment by prat1kbhujbal** [comment]
Thank you for your support.
