### ISSUE TITLE
Performance Issue (Extremely High CPU Usage)

### ISSUE THREAD

**Issue by borongyuan** [DreamVu/PAL-USB#15]
Hi,
When I installed the new SDK, I ran into a noticeable performance issue. This issue was also mentioned in my email to Rajat. He asked me to share the SavedPalProperties.txt file to check. So I attach the file here.
[SavedPalProperties.txt](https://github.com/DreamVu/PAL-USB/files/9886820/SavedPalProperties.txt)
But I don't think it's a setting issue. I barely changed any settings. Rajat told me that the default settings is expected to hit 20 FPS, so I did another clean install. I still only get 4-6 FPS, this file should be the default setting. I've noticed that the main problem is CPU usage, not model inference. So the problem could be with image preprocessing, postprocessing, or the Explorer itself?
![Screenshot from 2022-10-28 16-10-08](https://user-images.githubusercontent.com/22918715/198549940-863667e1-339e-4364-a2cb-a2489ab37b92.png)
Since I installed using Method 2, many dependencies are determined. The most likely differences are the system environment, and the installed Python packages. I tested using the Jetson Xavier NX Developer Kit, with JetPack 4.6.0 installed. Some packages installed in Python virtual environment do not have a version specified. I recorded their installed versions for comparison.
> Successfully installed pip-21.3.1 setuptools-59.6.0
Successfully installed cachetools-4.2.4 certifi-2022.9.24 charset-normalizer-2.0.12 google-api-core-2.8.2 google-api-python-client-2.52.0 google-auth-2.13.0 google-auth-httplib2-0.1.0 google-auth-oauthlib-0.7.0 googleapis-common-protos-1.56.3 httplib2-0.20.4 idna-3.4 oauthlib-3.2.2 protobuf-3.19.6 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-3.0.9 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.9 six-1.16.0 uritemplate-4.1.1 urllib3-1.26.12
Successfully installed absl-py-1.3.0 grpcio-1.48.2
Successfully installed Cython-0.29.32
Successfully installed numpy-1.19.3
Successfully installed imageio-2.15.0 opencv-python-4.6.0.66 pillow-8.4.0 pyyaml-6.0
Successfully installed pyparsing-3.0.8
Successfully installed catkin-pkg-0.5.2 docutils-0.18.1 python-dateutil-2.8.2
Successfully installed empy-3.3.4

**Comment by kishk31** [comment]
Dear Yuan,

Thanks for your patience.
We have fixed this issue in the latest release which will be available on github repo by 11th of November. 
Please make use of the fix.

**Comment by DreamVu-Support** [comment]
Welcome DreamVu/PAL-USB!
 

 You are invited to access DreamVu Customer Support&#39;s Customer Self Service Portal
 

 

 

 

 By accessing this portal, you can track your requests online,
 access knowledge base and join the community forums.
 ACCEPT THE INVITATION


 

 

 

 Your user name is ***@***.*** | You can also click here to accept the invitation 
 

 

 

 

 

 Thank you, DreamVu Customer Support Administrator
 

 

 



This email has been sent to you&#x28;reply&#x2b;a354cbnrxvpqtjp6bjo4wywbnzkdxevbnhhfkdnkda&#x40;reply.github.com&#x29; by rajat&#x40;dreamvu.com from DreamVu Customer Support. Please contact the sender&#x28;rajat&#x40;dreamvu.com&#x29; for any clarifications.

**Comment by kishk31** [comment]
Dear Yuan,

As promised the display bug has been fixed in the latest release which is live on Github.
So please use it - [(https://github.com/DreamVu/PAL-USB)]

**Comment by kishk31** [comment]
Dear Yuan,

As promised the display bug has been fixed in the latest release which is live on Github.
So please use it - [(https://github.com/DreamVu/PAL-USB)]
