### ISSUE TITLE
jetson_clocks command in rc.local not working

### ISSUE THREAD

**Issue by borongyuan** [DreamVu/PAL-USB#16]
Hi,
This is a known issue, please refer to the post on the NVIDIA forums.
https://forums.developer.nvidia.com/t/jetson-clocks-only-works-when-started-60-seconds-after-boot-why/148207

**Comment by kishk31** [comment]
Dear Yuan, 

Thanks for your patience.
This issue is known and will be resolved in the next release which is expected on 11th of Nov.

**Comment by DreamVu-Support** [comment]
Welcome DreamVu/PAL-USB!
 

 You are invited to access DreamVu Customer Support&#39;s Customer Self Service Portal
 

 

 

 

 By accessing this portal, you can track your requests online,
 access knowledge base and join the community forums.
 ACCEPT THE INVITATION


 

 

 

 Your user name is ***@***.*** | You can also click here to accept the invitation 
 

 

 

 

 

 Thank you, DreamVu Customer Support Administrator
 

 

 



This email has been sent to you&#x28;reply&#x2b;a354cbjmswar3h5lonrrzdobnzlpbevbnhhfkdnzmy&#x40;reply.github.com&#x29; by rajat&#x40;dreamvu.com from DreamVu Customer Support. Please contact the sender&#x28;rajat&#x40;dreamvu.com&#x29; for any clarifications.
