### ISSUE TITLE
libopenvino.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nyxrobotics** [DreamVu/PAL-USB#20]
I'm using a core i5 computer with no GPU + Ubuntu 18.04.
I followed the instructions and ran the following commands:
```bash
~/DreamVu/PAL/Explorer/x86_64/Explorer
```
Then I got the following error:
```bash
DreamVu/PAL/Explorer/x86_64/Explorer: error while loading shared libraries: libopenvino.so: cannot open shared object file: No such file or directory
```

**Comment by nyxrobotics** [comment]
I have the following additional questions:
- There is a repository named [SLAM](https://github.com/DreamVu/SLAM) with similar contents. What is this?
- I think the source code of binary files should be made public.
- The ros package should be in a separate repository so that it can be built without depending on the library

**Comment by DreamVu-Support** [comment]
Dear Numai,

Thanks for your patience. 
Can we please have a remote session via Zoom to resolve the error on your system.
A mail regarding the same has been sent to your mail id.

**Comment by kishk31** [comment]
Issue resolved via remote session.
