### ISSUE TITLE
Changing resolution doesnt work

### ISSUE THREAD

**Issue by LoicBoileau** [DreamVu/PAL-USB#22]
Hi,
I have been trying to change the PAL resolution by changing the using the SetCameraProperties() function like this: 
```
PAL::CameraProperties prop;
prop.resolution.height = 350;
prop.resolution.width = 760;
unsigned long int flags = PAL::ALL;
PAL::SetCameraProperties(&prop, &flags);
```

Yet the video stays with the same default quality of 224 and 672...

I think it is not working properly.

Let me know if I was doing something wrong.

Loic

**Comment by kishk31** [comment]
Dear Boileau,

Thanks for your patience.
Resolution width & height in video are output properties.
Currently displayed resolution is fixed it can't be changed.
